gg:
  jte:
    development-mode: true

spring:
  application:
    name: quiz

  security:
    user:
      name: admin
      password: 123456

  threads:
    virtual:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:postgresql://localhost:5433/quizdb
    username: quizuser
    password: quizpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 2123
  servlet:
    session:
      timeout: 10000m

anthropic:
  api:
    key: sk-ant-api03-BURAYA_COPY_ETDIYIN_KEY_GELIR
  model: claude-sonnet-4-20250514

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha